import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated by{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/necktipsone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            NecktipsOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/kneetipsone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            KneetipsOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/shouldertipsfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ShouldertipsFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/wristtipsthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            WristtipsThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/necktips" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Necktips
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/ankletipstwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AnkletipsTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/kneetipsthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            KneetipsThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/generaltipsix" style={{ color: "#87CEFA", textDecoration: "none" }}>
            GeneraltipsSix
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/ankletips1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Ankletips1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/home1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Home1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/ankletipsthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AnkletipsThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/wristtips1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Wristtips1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/wristtipsfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            WristtipsFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/necktipsfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            NecktipsFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/necktips1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Necktips1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/shouldertipsone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ShouldertipsOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/wristtipsone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            WristtipsOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/generaltips" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Generaltips
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/necktipsthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            NecktipsThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/kneetips" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Kneetips
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/shouldertipsthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ShouldertipsThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/wristtipstwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            WristtipsTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/necktipstwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            NecktipsTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/kneetipstwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            KneetipsTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/shouldertipstwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ShouldertipsTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/wristtips" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Wristtips
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/generaltipsone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            GeneraltipsOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/tips" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Tips
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/shouldertips" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Shouldertips
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/yogatrainers" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Yogatrainers
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/coreteam" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Coreteam
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/yoga" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Yoga
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/kneetips1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Kneetips1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/instructors" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Instructors
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/ankletips" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Ankletips
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/shouldertips1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Shouldertips1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/generaltipstwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            GeneraltipsTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/generaltips1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Generaltips1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/dietitians" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Dietitians
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/ankletipsone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AnkletipsOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/physiotherapists" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Physiotherapists
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/generaltipsthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            GeneraltipsThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/generaltipsfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            GeneraltipsFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/generaltipsfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            GeneraltipsFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/about" style={{ color: "#87CEFA", textDecoration: "none" }}>
            About
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;